# Generated by Django 5.2 on 2025-05-03 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0003_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='fichier_joint',
            field=models.FileField(blank=True, null=True, upload_to='fichiers_messages/'),
        ),
    ]
