# Generated by Django 5.2 on 2025-05-03 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0004_message_fichier_joint'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='telephone',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
